### ISSUE TITLE
How to update the device state?

### ISSUE THREAD

**Issue by klein0r** [lametric/Documentation#16]
I can set several devices states using the iOS App:

- auto - **auto scroll** mode, when device switch between apps automatically
- manual - **click to scroll** mode, when user can manually switch between apps
- schedule - **apps by time schedule**
- kiosk - kiosk mode when **single app** is locked on the device

How can I activate these states using the API?

**Comment by dbarysk** [comment]
@klein0r there is currently no official way of doing this.
