### ISSUE TITLE
Display response not fully documented

### ISSUE THREAD

**Issue by klein0r** [lametric/Documentation#18]
Documentation says:

```
{
  "brightness": <0-100>,
  "brightness_mode": "[auto|manual]",
  "height": 8,
  "width": 37,
  "type": "mixed",
  "screensaver": {
    "enabled": [true|false],
    "modes": {
      "time_based": {
        "enabled": [true|false]
        "start_time": "<time>"
        "end_time": "<time>",
      },
      "when_dark": {
        "enabled": [true|false]
      }
    },
    "widget": "<widget_uuid>"
  }
}
```

But the response is currently:

```
{
    "brightness": <0-100>,
    "brightness_limit": {
        "max": 75,
        "min": 2
    },
    "brightness_mode": "[auto|manual]",
    "brightness_range": {
        "max": 100,
        "min": 0
    },
    "height": 8,
    "width": 37,
    "type": "mixed",
    "screensaver": {
        "enabled": [true|false],
        "modes": {
            "time_based": {
                "enabled": [true|false],
                "end_time": "07:00:00",
                "local_end_time": "08:00:00",
                "local_start_time": "01:00:00",
                "start_time": "00:00:00"
            },
            "when_dark": {
                "enabled": [true|false]
            }
        },
        "widget": "<widget_uuid>"
    }
}
```

**Comment by sygys** [comment]
Im new to all this... im trying to get the current state of the display in home assistant. I want to use a sensor for this which gets the data using a get command. i have this GET http://192.168.0.233:8080/api/v2/device?fields=display. This gives the need to authorize error.

So i need to send the api key with this request. But nowhere in de docs is told how to do so. I succesfully implemented post command using the restcommand features within home assistant but getting is allot harder. So i want to use node red with the http request node and send a get command with the right url and with function node filter the data i need and post it back to Home assistant in a sensor i can use.

Does anyone have a clue how to do this?

**Comment by klein0r** [comment]
@sygys This is documented here: https://lametric-documentation.readthedocs.io/en/latest/reference-docs/device-authorization.html#step-3-store-api-key-and-use-it-in-every-api-request

You have to send the HTTP Authorization Header with the API Key

**Comment by klein0r** [comment]
@dbarysk ??

**Comment by sygys** [comment]
I have successfully fully implemented the lametric clock in home assistant using node red. Some features are missing which is a shame. It's strange that you can't play local files to for example use the clock as an alarm clock. Also playing own music or notifications. It's a pretty expensive clock to miss these kind of features. Also the problem that the clock can't be setup when there is no connection to the Lametric servers is a pain. It has nice local api's features but to get there you need to connect it to the Lametric servers first. Still I'm loving this device for it's features. Showing my indoor temperature everytime it change and then reverts back to the clock after 30 seconds. I even made an app with nothing on screen to fully shutdown the clock when no motion and light is on in the room to preserve the led's in the clock. It has allot of nice features

**Comment by dbarysk** [comment]
@klein0r thank you for reports, I have updated the docs.

**Comment by dbarysk** [comment]
@sygys thanks for your efforts and feedback. Actually, playing custom audio is a great feature and we were thinking about it internally. I think we will implement it eventually, super busy right now :).

As for the connecting a device to the cloud to use non cloud based features – good point. This is mainly related to the architecture of the system itself and is not that easy to get rid of in order to keep everything secure and reliable. But we are already on it. Big updates are coming soon.
