### ISSUE TITLE
Device response not fully documented

### ISSUE THREAD

**Issue by klein0r** [lametric/Documentation#19]
Example Reponse with Version 2.2.1

BLE information are missing in documentation:

```
"low_energy": {
   "active": true,
   "advertising": true,
   "connectable": true
},
```

**Comment by dbarysk** [comment]
Currently every device has Bluetooth Low Enerty active at all times and it can't be turned off. That is why this API is not that useful. It is better to avoid using "low_energy" object in any integrations as we can eventually change or remove any undocumented things. Not adding it to the docs yet until we see any useful use cases.

**Comment by klein0r** [comment]
Thanks! Maybe you should add that hint to the docs?
